name: Release
on:
  push:
    tags:
      - 'v*-beta.*'
    paths:
      - 'installer/**'  # Only trigger on changes in installer directory

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: ./installer  # Set default working directory

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './installer/package-lock.json'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
          npm install

      - name: Install dependencies (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          rustup target add aarch64-apple-darwin
          npm install

      - name: Install dependencies (windows)
        if: matrix.platform == 'windows-latest'
        run: |
          rustup target add x86_64-pc-windows-msvc
          npm install

      - name: Build Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: './installer'  # Point to your Tauri project
          tagName: ${{ github.ref_name }}
          releaseName: 'Smithery Beta ${{ github.ref_name }}'
          releaseBody: 'Beta release - for testing purposes only.'
          releaseDraft: false
          prerelease: true 